import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/components/navbar/Navbar";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import localFont from "next/font/local";

import Head from "next/head";
import Topbar from "@/app/components/navbar/Topbar";
import { SearchBarContextProvider } from "@/app/components/context/SearchBarContext";

const myFont = localFont({
  src: "../font/SuisseIntl-Medium.woff",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="theme-color" content="#ecd96f" />
      </Head>
      <body className={` ${myFont.className}`}>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <SearchBarContextProvider>
          <Topbar />
          <div className="flex bg-[#e2f1e2]">
            <Navbar />

            <div className="page main-content bg-[#e2f1e2] min-h-screen">
              <main className="">{children}</main>
            </div>
          </div>
        </SearchBarContextProvider>
      </body>
    </html>
  );
}
